version: '3.9'

services:
  portfolio-prod:
    container_name: audrey-schmidt-portfolio-prod
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - './:/app'
    ports:
      - "8080:8080"